version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_db
    ports:
      - 54320:5432
  redis:
    image: "redis:alpine"
  read-websites-api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:80
    links:
      - celery
      - celery-beat
      - redis
      - db
  celery:
    build: .
    command: celery -A semantive.controller.main.celery worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A semantive.controller.main.celery beat -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
